---
title: "Bias Variance Tradeoff"
output: html_notebook
---


```{r}
library(tidyverse)
library(ISLR)
library(ggplot2)
```



See slide 20 for implimentation:

https://web.engr.oregonstate.edu/~tgd/classes/534/slides/part9.pdf



```{r}
num_boot <- 200

degrees <- 1:10

resample_boot_oob <- function(data, n, id = ".id"){
  # function to create bootstrap along with out of bag indexes
  tot_length <- nrow(data)
  
  boot_samples <- lapply(1:n, function(x){
    sample(tot_length, tot_length, replace = T)
  })
  
  oob_samples <- lapply(boot_samples, function(x){
    (1:tot_length)[!(1:tot_length %in% x)]
  })
  
  
  
  out <- tibble(
    boot_sample = boot_samples,
    oob_samples = boot_samples
  )
  
  out[[id]] <- 1:n
  out
}

# Slide 20
# first bullet/ third_bullet
boot_df <- resample_boot_oob(Auto,num_boot)
boot_df <- boot_df %>% 
  crossing(degrees = c(1, 5, 10, 16))

# second bullet
boot_df <- boot_df %>% 
  mutate(lm_mod = map2(degrees, boot_sample, ~lm(mpg ~ poly(horsepower, degree = .x), data = Auto[.y, ])))


# fourth

boot_df <- boot_df %>% 
  mutate(h_b = map2(lm_mod, oob_samples, ~predict(.x, Auto[.y, ]))) %>% 
  mutate(each_df  = map2(oob_samples, h_b, ~tibble(
    index = .x,
    predicted = .y,
    actual = Auto$mpg[.x]
  )))

```


```{r}

# clean up/Slide 21

analytical_df <- boot_df %>% 
  select(.id, degrees, each_df) %>% 
  unnest()

analytical_df %>% 
  group_by(degrees, index) %>% 
  mutate(hbar = mean(predicted)) %>% 
  summarise(bias_sq_mod = mean((predicted - actual)^2),# mean is necessary just to condense to one row
            var_mod = var(predicted)) %>% 
  group_by(degrees) %>% 
  summarise_at(vars(bias_sq_mod, var_mod), mean, na.rm = T)
  
```

```{r}




```

