---
title: "Evaluate Submissions"
output: html_notebook
---

```{r}
library(dplyr)
library(readr)
library(readxl)
```

# Group 1 - Bank

```{r}
group1_raw <- readxl::read_excel('final_projects/submissions/Group 1/predictdi.xlsx')
group1 <- group1_raw %>% 
  select(id, pred = y)
```

# Group 2 - Bank
```{r}
group2_raw <- read_csv("final_projects/submissions/Group 2/Codes & prediction test data - Archive/final_predicted data.csv")
group2 <- group2_raw %>% 
  select(id, pred = y)
```

# Group 3 - Wine Quality
```{r}
group3_raw <- read_xls('final_projects/submissions/Group 3/regression test.xls')
group3 <- group3_raw %>% 
  select(id,pred = quality)   
```

# Group 4 - Bank
```{r}
group4_raw <- read_csv('final_projects/submissions/Group 4/group_4_test_predictions.csv')
group4 <- group4_raw %>% 
  select(id, pred = test.predictions)
```

# Group 5 - Online

```{r}
group5_raw <- read_csv('final_projects/submissions/Group 5/pred_data.csv')
group5 <- group5_raw %>% 
  select(id, pred = shares)
```

# Group 6 - Wine

```{r}
group6_raw <- read_csv('final_projects/submissions/Group 6/wine_predicted_value.csv')
group6 <- group6_raw %>% 
  select(id, pred = predict)
```

# Group 7 - Wine

```{r}
group7_raw <- read_csv('final_projects/submissions/Group 7/FinalWineTestPredictions.csv')
group7 <- group7_raw %>% 
  select(id, pred = quality)

```
# Group 8 - Wine

```{r}
group8_raw <- read_csv('final_projects/submissions/Group 8/test_data_prediction.csv')
group8 <- group8_raw %>% 
  select(id, pred = Prediction)

```

```{r}
evalBank <- function(df){
  answers <- suppressMessages(read_csv('final_projects/bank/transformed/test_data_lab.csv'))
  
  if(nrow(answers) != nrow(df)){
    warning("Answers: ", nrow(answers), "\n",
            "Predicted: ", nrow(df), "\n")
    
  }
  df <- df %>% 
    left_join(answers, by = "id")
  list(
    accuracy = with(df, mean(pred == actual)),
    confMat = xtabs(~pred + actual, data = df)
  )
}

evalWine <- function(df){
  answers <- suppressMessages(read_csv('final_projects/wine/transformed/test_data_lab.csv'))
  df <- df %>% 
    left_join(answers, by = "id")
  
  list(
    mse = with(df, mean((pred-actual)^2))
  )
}

evalOnline <- function(df){
  answers <- suppressMessages(read_csv('final_projects/onlinenews/transformed/test_data_lab.csv'))
  df <- df %>% 
    left_join(answers, by = "id")
  
  list(
    mse = with(df, mean((pred-actual)^2))
  )
  
  
}



```



# Evaluations
```{r}
evalBank(group1)
evalBank(group2)
evalWine(group3)
evalBank(group4)
evalOnline(group5)
evalWine(group6)
evalWine(group7)
evalWine(group8)


```
