---
title: "R Notebook"
output: pdf_document
---

```{r, include = FALSE}
library(tidyverse)
library(purrr)
library(tidyr)
library(caret)
library(ggplot2)
library(ISLR)
theme_set(theme_minimal())

```


# PCA


```{r}

USArrests %>% glimpse

```

```{r}
pr<-prcomp(USArrests, scale=TRUE)

pr %>% summary

biplot(pr, scale=0)

```

Variance explained

```{r}

pr$sdev
```


# Clustering

## K Means Clustering


```{r}
d <- data.frame(
  x1 = rnorm(n = 1000),
  x2 = rnorm(1000)
)

cluster <- rnorm(nrow(d)) > 0


d <- d %>% 
  mutate(x1 = ifelse(cluster, x1 + 2, x1),
         x2 = ifelse(cluster, x2 -2, x2))

d %>% 
  ggplot(aes(x = x1, y = x2)) +
  geom_point()

```


Randomily assign each point to K clusters


```{r wi}
k <- 3
k_seq <- 1:k

d$assign <- sample(k_seq, size = nrow(d), replace = T)

centroids <- d %>% 
  group_by(assign) %>% 
  summarise_at(vars(x1, x2), funs(cent = mean))

iteration <- 1
d %>% 
  ggplot(aes(x = x1, y = x2, color = as.factor(assign))) +
  geom_point( alpha = 0.7) +
  geom_point(aes(x = x1_cent, y = x2_cent), data = centroids, size = 8, alpha = 0.8) +
  labs(title = paste0("Iteration: ", iteration))

d$assign <- NULL
cent_old <- data.frame()

while(is.character(all_equal(cent_old, centroids)) & iteration <= 100){
  iteration <- iteration + 1
  d <- d %>% 
    crossing(centroids) %>% 
    mutate(euc_dist = sqrt((x1_cent - x1)^2 + (x2_cent - x2)^2)) %>% 
    group_by(x1,x2) %>% 
    filter(euc_dist == min(euc_dist)) %>% 
    select(x1, x2, assign)
  
  cent_old <- centroids
  centroids <- d %>% 
    group_by(assign) %>% 
    summarise_at(vars(x1, x2), funs(cent = mean))
  
  d_plot <- d %>% 
    ggplot(aes(x = x1, y = x2, color = as.factor(assign))) +
    geom_point( alpha = 0.7) +
    geom_point(aes(x = x1_cent, y = x2_cent), data = centroids, size = 8, alpha = 0.8)  +
  labs(title = paste0("Iteration: ", iteration)) +
    theme(legend.position = "none")
  print(d_plot)
  d$assign <- NULL
}

d <- d %>% 
    crossing(centroids) %>% 
    mutate(euc_dist = sqrt((x1_cent - x1)^2 + (x2_cent - x2)^2)) %>% 
    group_by(x1,x2) %>% 
    filter(euc_dist == min(euc_dist)) %>% 
    select(x1, x2, assign)





```
### Kmeans lab

```{r}

d_mat <- d %>% 
  select(-assign) %>% 
  as.matrix()

centroids
kmeans(d_mat, centers = k)$centers




```


## Hierarchichcal Clustering

```{r}
h_clust <- hclust(dist(scale(d_mat)), method = "complete") 

h_clust %>% 
  plot()

# method: average, single

cutree(h_clust, 2)
```

```{r}



```

