---
title: "STAT 716 - Class 4 - 2018-09-24""
author: "Vitaly Druker"
date: "9/24/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


Odds ratio vs probability

```{r}
probs <- seq(0,1, length.out = 1000)

or <- probs/(1-probs)


data.frame(probs, or) %>% 
  ggplot(aes(x = probs, y = or)) + 
  geom_point()

data.frame(probs, or) %>% 
  filter(probs < .1) %>% 
  ggplot(aes(x = probs, y = or)) + 
  geom_point() + 
  geom_abline(slope = 1, intercept = 0)

data.frame(probs, or) %>% 
  filter(probs < .05) %>% 
  ggplot(aes(x = probs, y = or)) + 
  geom_point() + 
  geom_abline(slope = 1, intercept = 0)


```



```{r}
library(ISLR)

main_data <- Default
```





```{r}
main_data <- main_data %>% 
  mutate(default_num = as.numeric(default == "Yes"))

main_data %>% glimpse

```


```{r}
Default %>% 
  mutate(default_num = as.numeric(default=="Yes")) %>% 
  ggplot(aes(x = balance, y = default_num)) + 
  geom_point() +
  geom_smooth(method = "lm")


Default %>% 
  mutate(default_num = as.numeric(default=="Yes")) %>% 
  ggplot(aes(x = balance, y = default_num)) + 
  geom_point() +
  geom_smooth(method = "glm", 
              method.args = list(family = "binomial"))

```


```{r}
lm(default_num ~ balance, data = main_data) %>% 
  summary
```


```{r}
glm(default ~ balance, data = main_data, family = "binomial") %>% 
  summary
```

```{r}
glm(default ~ student, data = main_data, family = "binomial") %>% 
  summary

exp(.40489)
```


Non student?

```{r}
exp(-3.504)/(1+exp(-3.504))
```



If you have two people with the only difference being one is a student what is the probability that the student defaults given that the other person's chance of default is 3%

```{r}
exp(-3.504 + .404)/(1+exp(-3.504 + .404))
```


```{r}
glm(default ~ ., data = main_data, family = "binomial") %>% 
  summary
```

Confounding?


```{r}

ggplot(main_data, aes(x = student, y = balance)) +
  geom_boxplot()


ggplot(main_data, aes(x = student, y = income)) +
  geom_boxplot()
```

Prediction

```{r}

models <- glm(default_num ~ student, data = main_data, family = "binomial")

predict(models, data.frame(student = "Yes"))

predict(models, data.frame(student = "No"), type = "response")


```


# Linear Discrimenant Analysis

```{r}

lda(default_num ~ student, data = main_data) %>% plot

```

