---
title: "Class 6"
output: html_notebook
---



```{r}
library(ISLR)
library(dplyr)
library(ggplot2)
```

# Validation Approach

```{r}
set.seed(2)

testAutoDataValidation <- function(poly_degrees, train_set){
  
  mod <- lm(mpg ~ poly(horsepower, poly_degrees), data = Auto[train_set, ])
  pred_values <- predict(mod, Auto)
  mean((pred_values[-train_set] - Auto$mpg[-train_set])^2)
}


tot_n <- nrow(Auto)

num_trys <- 5

degrees <- 1:10 

final_df <- data.frame()

for(i in 1:num_trys){
  
  train_set <- sample(x = 1:tot_n, size = floor(.7*tot_n))
  cur_test_mse <- sapply(degrees,testAutoDataValidation, train_set = train_set)
  
  final_df <- bind_rows(final_df, 
            data.frame(
              try = i,
              degrees = degrees,
                       test_mse = cur_test_mse))

}

final_df %>% 
  ggplot(aes(x = degrees,
              y = test_mse,
             color = as.factor(try))) +
  geom_line() +
  theme(legend.position = "none")

```

# LOOCV


 there is a shortcut in the book - but we will not review
 
```{r}


final_df <- data.frame()

for(i in 1:tot_n){
  
  cur_test_mse <- sapply(degrees,testAutoDataValidation, train_set = -i)
  
  final_df <- bind_rows(final_df, 
            data.frame(
              try = i,
              degrees = degrees,
                       test_mse = cur_test_mse))
}



final_df %>% 
  group_by(degrees) %>% 
  summarise(test_mse = mean(test_mse)) %>% 
  ggplot(aes(x = degrees,
              y = test_mse)) +
  geom_line() +
  theme(legend.position = "none")

```

```{r}

```



# K Fold CV

```{r}
num_folds <- 10
final_df <- data.frame()
fold_assignment <- rep_len(1:num_folds, length.out = tot_n)
fold_assignment <- sample(fold_assignment)

for(i in 1:num_folds){
  cur_test_mse <- sapply(degrees, testAutoDataValidation, 
                         train_set = (1:tot_n)[fold_assignment!=i])
  final_df <- bind_rows(final_df, 
            data.frame(
              try = i,
              degrees = degrees,
                       test_mse = cur_test_mse))
}




final_df %>% 
  group_by(degrees) %>% 
  summarise(test_mse = mean(test_mse)) %>% 
  ggplot(aes(x = degrees,
              y = test_mse)) +
  geom_line() +
  theme(legend.position = "none")
```

How do we actually select a model?
We are trying to find the underlying data generating process.


# Bootstrapping

```{r}
alpha_fun <- function(data, index){
  x <- data$X[index]
  y <- data$Y[index]
  
  (var(y) - cov(x,y))/(var(x) + var(y) - 2*cov(x,y))
  
  
}

sample(nrow(Portfolio), nrow(Portfolio), replace = TRUE) %>% sort

num_boot <- 1000

out <- rep(0, num_boot)

set.seed(1)
for(i in 1:num_boot){
  boot_samp <- sample(nrow(Portfolio), nrow(Portfolio), replace = T)
  out[i] <- alpha_fun(Portfolio,  boot_samp)
}


mean(out)
sd(out)

quantile(out, c(.25, .5, .75))
hist(out)

library(boot)
boot(Portfolio, alpha_fun, R = 1000) 

alpha_fun(Portfolio, 1:nrow(Portfolio))
```


# How much data do I need?

```{r}

set.seed(5)

testAutoDataSize <- function(poly_degrees, train_set, test_set){
  
  mod <- lm(mpg ~ poly(horsepower, poly_degrees), data = Auto[train_set, ])
  pred_values <- predict(mod, Auto)
  mean((pred_values[test_set] - Auto$mpg[test_set])^2)
}


test_size <- .2
num_runs <- 400
train_sizes <- floor(seq(10, (tot_n*(1-test_size)), length.out = 10))

data_size_df <- data.frame()

for( i in 1:10){
  test_set_ind <- sample(tot_n, size = .2*tot_n)
  train_set_ind <- (1:tot_n)[-test_set_ind]
  
  size_mse <- sapply(train_sizes, function(x){
    train_data_sample <- sample(train_set_ind, x)
    
    testAutoDataSize(2, train_set = train_data_sample, test_set = test_set)
    
  })
  
  data_size_df <- bind_rows(data_size_df, 
            data.frame(
              try = i,
              data_size =  train_sizes,
                       test_mse = size_mse))
}



data_size_df %>% 
  group_by(data_size) %>% 
  summarise(test_sde = sd(test_mse),
            low_q = quantile(test_mse, .25),
            high_q = quantile(test_mse, .75),
    test_mse = mean(test_mse)) %>% 
  ggplot(aes(x = data_size,
              y = test_mse,
             ymin = low_q,
             ymax = high_q)) +
  geom_pointrange() +
  theme(legend.position = "none")

```





